language:
  version: weekly.2025.43
  files:
    - "**/*.v"
    - server
  bootstrap:
    - cd /opt/vlang && git fetch --all --tags && git checkout weekly.2025.43 && make && v -version && cd /app && v install https://github.com/enghitalo/vanilla_http_server

  build_flags:
    - -prod -cc gcc

  engines:
    default:
      command: /app/server

framework:
  engines:
    - default
